import dotenv from "dotenv";
dotenv.config();

const env_config = {
  SERVER_PORT: process.env.SERVER_PORT,
  CLIENT_PORTS: process.env.CLIENT_PORTS,
  CLIENT_URL: process.env.CLIENT_URL,
  DB_URI: process.env.DB_URI,
  DB_NAME: process.env.DB_NAME,
  HASH_PASSWORD_SECRET: process.env.HASH_PASSWORD_SECRET,
  CLOUDINARY: {
    CLOUD_NAME: process.env.CLOUDINARY_CLOUD_NAME,
    API_KEY: process.env.CLOUDINARY_API_KEY,
    API_SECRET: process.env.CLOUDINARY_API_SECRET,
  },
  DB_COLLECTIONS: {
    USERS: process.env.DB_COLLECTION_USERS,
    POSTS: process.env.DB_COLLECTION_POSTS,
    COMMENTS: process.env.DB_COLLECTION_COMMENTS,
    REFRESH_TOKENS: process.env.DB_COLLECTION_REFRESH_TOKENS,
    CHATS: process.env.DB_COLLECTION_CHATS,
    IMAGES: process.env.DB_COLLECTION_IMAGES,
    VIDEOS: process.env.DB_COLLECTION_VIDEOS,
    MESSAGES: process.env.DB_COLLECTION_MESSAGES,
    FAVORITES: process.env.DB_COLLECTION_FAVORITES,
    LIKES: process.env.DB_COLLECTION_LIKES,
    REPORTS: process.env.DB_COLLECTION_REPORTS,
    FRIENDS: process.env.DB_COLLECTION_FRIENDS,
    NOTIFICATIONS: process.env.DB_COLLECTION_NOTIFICATIONS,
  },
  EMAIL_HOST: process.env.EMAIL_HOST,
  EMAIL_PORT: process.env.EMAIL_PORT,
  EMAIL_AUTH_USER: process.env.EMAIL_AUTH_USER,
  EMAIL_AUTH_PASS: process.env.EMAIL_AUTH_PASS,
  EMAIL_SERVICE: process.env.EMAIL_SERVICE,
  EMAIL_SERCURE: process.env.EMAIL_SERCURE,
  ACCESS_TOKEN_SECRET_KEY: process.env.ACCESS_TOKEN_SECRET_KEY,
  ACCESS_TOKEN_EXPIRES_IN: process.env.ACCESS_TOKEN_EXPIRES_IN,
  REFRESH_TOKEN_EXPIRES_IN: process.env.REFRESH_TOKEN_EXPIRES_IN,
  EMAIL_VERIFY_TOKEN_EXPIRES_IN: process.env.EMAIL_VERIFY_TOKEN_EXPIRES_IN,
  FORGOT_PASSWORD_TOKEN_EXPIRES_IN:
    process.env.FORGOT_PASSWORD_TOKEN_EXPIRES_IN,
  REFRESH_TOKEN_SECRET_KEY: process.env.REFRESH_TOKEN_SECRET_KEY,
  EMAIL_VERIFICATION_SECRET_KEY: process.env.EMAIL_VERIFICATION_SECRET_KEY,
  FORGOT_PASSWORD_SECRET_KEY: process.env.FORGOT_PASSWORD_SECRET_KEY,
};

export default env_config;
